import { inngest } from '../client'
import { ConvexHttpClient } from 'convex/browser'
import { api } from '../../convex/_generated/api'
import { ChatOpenAI } from '@langchain/openai'

const convex = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL!)

export const summarizeDiscussionJob = inngest.createFunction(
  {
    id: 'summarize-discussion',
    triggers: { event: 'board/discussion.summarize' },
  },
  async ({ event, step }: any) => {
    const { boardId, timeframe, startDate, endDate } = event.data

    const messages = await step.run('Fetch messages', async () => {
      return await convex.query(api.discussions.getMessagesForSummary, {
        boardId,
        timeframe,
        startDate,
        endDate,
      })
    })

    if (messages.length === 0) {
      return { success: false, reason: 'No messages found' }
    }

    const summary = await step.run('Generate Summary via Gemma 4', async () => {
      const chat = new ChatOpenAI({
        apiKey: process.env.OPENROUTER_API_KEY || 'dummy',
        configuration: {
          baseURL: 'https://openrouter.ai/api/v1',
        },
        modelName: 'google/gemma-4-31b-it:free',
        temperature: 0.3,
      })

      const messageContext = messages
        .map((m: any) => `${m.authorName}: ${m.content}`)
        .join('\n')

      const response = await chat.invoke([
        [
          'system',
          'You are an expert discussion summarizer. Provide a concise, structured summary of the following conversation. Highlight key points, decisions made, and pending questions.',
        ],
        ['user', `Summarize this conversation:\n\n${messageContext}`],
      ])

      return response.content as string
    })

    await step.run('Save summary as system message', async () => {
      await convex.mutation(api.discussions.sendSystemMessage, {
        boardId,
        content: `### 📝 Discussion Summary\n\n${summary}\n\n*Generated by AI*`,
        authorName: 'AI Summarizer',
      })
    })

    return { success: true, boardId }
  },
)
